# Generated by Django 3.2.9 on 2022-03-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eld', '0002_alter_drivers_co_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='co_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eld.drivers'),
        ),
    ]
