# Generated by Django 3.2.9 on 2022-03-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld', '0003_alter_drivers_co_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='trail_number',
        ),
        migrations.AddField(
            model_name='drivers',
            name='trail_number',
            field=models.ManyToManyField(blank=True, null=True, to='eld.Trailer'),
        ),
    ]
