# Generated by Django 3.2.9 on 2022-03-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('untilbreak', models.TimeField()),
                ('shift', models.TimeField()),
                ('cycle', models.TimeField()),
                ('worked_hours', models.TimeField()),
                ('current_status', models.TimeField()),
                ('errors', models.TextField()),
                ('dvir', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eld.drivers')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eld.vehicle')),
            ],
        ),
    ]
