# Generated by Django 3.2.9 on 2022-03-19 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmodel',
            name='cycle_tomorrow',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logmodel',
            name='driving',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='logmodel',
            name='driving_in_violation',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logmodel',
            name='duty_status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON'), ('SB', 'SB'), ('D', 'D')], max_length=50, null=True),
        ),
    ]
