# Generated by Django 3.2.9 on 2022-03-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eld', '0004_auto_20220328_1007'),
        ('event', '0004_auto_20220313_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=50)),
                ('shipping_doc', models.CharField(max_length=150)),
                ('main_ofice', models.CharField(max_length=150)),
                ('carrier', models.CharField(max_length=150)),
                ('home_terminal_address', models.CharField(max_length=150)),
                ('co_driver', models.CharField(max_length=150)),
                ('from_address', models.CharField(max_length=150)),
                ('to_address', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eld.drivers')),
                ('trailers', models.ManyToManyField(blank=True, null=True, to='eld.Trailer')),
                ('vehicles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eld.vehicle')),
            ],
        ),
    ]
